"""Markdown Renderer (architecture.md Section 10).

Pure/deterministic: the same (already sensitive-filtered, TASK-008) model
input and hash table (TASK-009) always produce the same Markdown text.
Renders an explicit "_Not available_" marker for any UNAVAILABLE field
so a genuinely missing docstring is never confused with an empty one.
"""

from __future__ import annotations

from docsync.changedetect import serialize_hash_table
from docsync.model import NOT_APPLICABLE, UNAVAILABLE, ClassDoc, FunctionDoc, ModuleDoc, ParameterDoc

NOT_AVAILABLE_MARKER = "_Not available_"

_DO_NOT_EDIT_NOTICE = "DO NOT EDIT — auto-generated by Automated Documentation Sync"


def _docstring_block(docstring: object) -> str:
    # Identity check (not truthiness): a genuinely empty docstring ("")
    # is a determined value and must render distinguishably from
    # UNAVAILABLE ("could not be determined"), per architecture Section 9.
    if docstring is UNAVAILABLE:
        return NOT_AVAILABLE_MARKER
    return str(docstring)


def _format_parameter(param: ParameterDoc) -> str:
    text = param.name
    if param.annotation is not UNAVAILABLE:
        text += f": {param.annotation}"
    if param.default is not NOT_APPLICABLE:
        text += f" = {param.default}"
    return text


def _format_signature(func: FunctionDoc) -> str:
    lines = [f"@{decorator}" for decorator in func.decorators]
    params = ", ".join(_format_parameter(p) for p in func.parameters)
    signature = f"def {func.name}({params})"
    if func.return_annotation is not UNAVAILABLE:
        signature += f" -> {func.return_annotation}"
    signature += ":"
    lines.append(signature)
    return "\n".join(lines)


def _render_function(func: FunctionDoc, heading_level: int) -> list[str]:
    heading = "#" * heading_level
    return [
        f"{heading} `{func.name}`",
        "",
        "```python",
        _format_signature(func),
        "```",
        "",
        _docstring_block(func.docstring),
        "",
    ]


def _render_class(cls: ClassDoc) -> list[str]:
    lines = [f"### `{cls.name}`", ""]
    if cls.decorators:
        lines.append(", ".join(f"`@{d}`" for d in cls.decorators))
        lines.append("")
    lines.append(_docstring_block(cls.docstring))
    lines.append("")
    for method in cls.methods:
        lines.extend(_render_function(method, heading_level=4))
    return lines


def _render_module(module: ModuleDoc) -> list[str]:
    lines = [f"## {module.path}", "", _docstring_block(module.docstring), ""]
    for cls in module.classes:
        lines.extend(_render_class(cls))
    for func in module.functions:
        lines.extend(_render_function(func, heading_level=3))
    return lines


def render(modules: list[ModuleDoc], hash_table: dict[str, str]) -> str:
    lines = [
        f"<!-- docsync:v1 sha256={serialize_hash_table(hash_table)} -->",
        f"<!-- {_DO_NOT_EDIT_NOTICE} -->",
        "",
        f"> **Do not edit this file by hand.** {_DO_NOT_EDIT_NOTICE}. "
        "Manual edits will be overwritten on the next run.",
        "",
    ]
    for module in sorted(modules, key=lambda m: m.path):
        lines.extend(_render_module(module))
    return "\n".join(lines).rstrip("\n") + "\n"
